name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Actualizar repositorio local con rebase
        run: git pull --rebase origin main

      - name: Copia los archivos actualizados desde el repositorio a la misma ubicación del repositorio
        run: cp -r /home/ubuntu/CLOUD_GPS/* /home/ubuntu/CLOUD_GPS/
